use crate::{
    agent_status::cmd_agent_status,
    agent_uninstall::{AgentUninstallTarget, cmd_agent_uninstall},
    codex_config::enable_codex_hooks_feature,
    util::{env_path_or_home, read_json_object, read_toml_document, write_json, write_text},
};
use anyhow::{Context, Result};
use clap::{Subcommand, ValueEnum};
use gommage_core::runtime::HomeLayout;
use serde::Serialize;
use std::{path::Path, process::ExitCode};

pub(crate) const CODEX_GOMMAGE_MATCHER: &str = "^Bash$|^apply_patch$|^mcp__.*$";
pub(crate) const CLAUDE_GOMMAGE_HOOK_COMMAND: &str = "gommage hook --agent claude";
pub(crate) const CODEX_GOMMAGE_HOOK_COMMAND: &str = "gommage hook --agent codex";

pub(crate) fn codex_pre_tool_use_path(root: &serde_json::Value) -> &'static [&'static str] {
    if root.pointer("/hooks/PreToolUse").is_some() {
        &["hooks", "PreToolUse"]
    } else {
        &["PreToolUse"]
    }
}

pub(crate) fn codex_pre_tool_use_pointer(root: &serde_json::Value) -> &'static str {
    if root.pointer("/hooks/PreToolUse").is_some() {
        "/hooks/PreToolUse"
    } else {
        "/PreToolUse"
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, ValueEnum, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum AgentKind {
    Claude,
    Codex,
}

impl AgentKind {
    pub(crate) fn as_str(self) -> &'static str {
        match self {
            Self::Claude => "claude",
            Self::Codex => "codex",
        }
    }
}

#[derive(Subcommand)]
pub enum AgentCmd {
    /// Install a PreToolUse hook for a supported agent.
    Install {
        #[arg(value_enum)]
        agent: AgentKind,
        /// Replace existing PreToolUse hook groups instead of preserving them.
        #[arg(long)]
        replace_hooks: bool,
        /// Skip importing native agent permission rules into Gommage policy.
        #[arg(long)]
        no_import_native_permissions: bool,
        /// Show planned file edits without writing them.
        #[arg(long)]
        dry_run: bool,
    },
    /// Remove a supported agent integration.
    Uninstall {
        #[arg(value_enum)]
        agent: AgentUninstallTarget,
        /// Restore the newest validated .gommage-bak-* backup instead of only removing the hook.
        #[arg(long)]
        restore_backup: bool,
        /// Show planned file edits without writing them.
        #[arg(long)]
        dry_run: bool,
    },
    /// Inspect whether a supported agent integration is wired correctly.
    Status {
        #[arg(value_enum)]
        agent: AgentKind,
        /// Emit a stable machine-readable status report.
        #[arg(long)]
        json: bool,
    },
}

pub fn cmd_agent(sub: AgentCmd, layout: HomeLayout) -> Result<ExitCode> {
    match sub {
        AgentCmd::Install {
            agent,
            replace_hooks,
            no_import_native_permissions,
            dry_run,
        } => {
            install_agent(
                agent,
                &layout,
                replace_hooks,
                !no_import_native_permissions,
                dry_run,
            )?;
            Ok(ExitCode::SUCCESS)
        }
        AgentCmd::Uninstall {
            agent,
            restore_backup,
            dry_run,
        } => cmd_agent_uninstall(agent, restore_backup, dry_run),
        AgentCmd::Status { agent, json } => cmd_agent_status(agent, &layout, json),
    }
}

pub fn install_agent(
    agent: AgentKind,
    layout: &HomeLayout,
    replace_hooks: bool,
    import_native_permissions: bool,
    dry_run: bool,
) -> Result<()> {
    if !dry_run {
        layout.ensure().context("initializing home")?;
    }
    write_agent_posture_policy(layout, dry_run)?;
    match agent {
        AgentKind::Claude => {
            let path = env_path_or_home("GOMMAGE_CLAUDE_SETTINGS", &[".claude", "settings.json"]);
            install_claude(
                &path,
                layout,
                replace_hooks,
                import_native_permissions,
                dry_run,
            )
        }
        AgentKind::Codex => {
            let hooks_path = env_path_or_home("GOMMAGE_CODEX_HOOKS", &[".codex", "hooks.json"]);
            let config_path = env_path_or_home("GOMMAGE_CODEX_CONFIG", &[".codex", "config.toml"]);
            install_codex(&hooks_path, &config_path, replace_hooks, dry_run)
        }
    }
}

/// `06-agent-config-writable.yaml` — loads before `10-filesystem` so the
/// blanket `fs.write:${HOME}/.*` deny (its glob `*` crosses `/`) cannot lock the
/// agent out of editing its OWN config dirs. Credential dirs stay denied by 10.
const AGENT_CARVE_OUT_YAML: &str = r#"# Agent-managed config dirs — writable carve-out.
#
# Generated by `gommage agent install`. Loads BEFORE 10-filesystem so first-match
# makes these allows beat 10's `no-writes-to-home-dotfiles` blanket deny
# (`fs.write:${HOME}/.*`, whose glob `*` crosses `/` and would otherwise stop the
# agent from editing its own configuration under these dot-dirs).
#
# Scope is limited to the trees an agent legitimately owns. Credential dirs
# (.ssh/.aws/.gnupg) are NOT carved out here — 10-filesystem still denies them —
# and secret READS stay denied by the 05 import layer regardless of this file.

- name: agent-config-writable-claude
  decision: allow
  match:
    any_capability:
      - "fs.write:${HOME}/.claude/**"
  reason: "agent maintains its own Claude Code config under ~/.claude"

- name: agent-config-writable-codex
  decision: allow
  match:
    any_capability:
      - "fs.write:${HOME}/.codex/**"
  reason: "agent maintains its own Codex config under ~/.codex"

- name: agent-config-writable-gommage
  decision: allow
  match:
    any_capability:
      - "fs.write:${HOME}/.gommage/**"
  reason: "agent maintains its own Gommage policy home under ~/.gommage"
"#;

/// `95-agent-catch-all.yaml` — loads after every gate so they win first, then
/// flips the evaluator's fail-closed default: anything not stopped is allowed.
const AGENT_CATCH_ALL_YAML: &str = r#"# Catch-all allow — fail-open EXCEPT gates.
#
# Generated by `gommage agent install`. Loads AFTER every hard-stop, deny, and
# gate (00 hard-stops, 05 import denies, 10 filesystem, 15 agent-tools, 20 git,
# 30 pkg, 40 cloud, 50 cloud-tools), all of which win first. This flips the
# evaluator's built-in "no rule matched -> fail-closed deny": anything the layers
# above did not stop falls through to ALLOW here.
#
# Every Bash call always emits `proc.exec:<command>`, so `proc.exec:**` catches
# any shell the gates did not stop; Read/Glob -> fs.read, Write/Edit -> fs.write.
# Delete this file to return the agent to a strict fail-closed posture.

- name: agent-catch-all-proc-exec
  decision: allow
  match:
    any_capability:
      - "proc.exec:**"
  reason: "catch-all: shell not stopped by an earlier gate/deny is allowed"

- name: agent-catch-all-fs-read
  decision: allow
  match:
    any_capability:
      - "fs.read:**"
      - "fs.search:**"
  reason: "catch-all: reads/searches not denied by an earlier secret rule are allowed"

- name: agent-catch-all-fs-write
  decision: allow
  match:
    any_capability:
      - "fs.write:**"
  reason: "catch-all: writes not denied by an earlier dotfile/build rule are allowed"

- name: agent-catch-all-net-out
  decision: allow
  match:
    any_capability:
      - "net.out:**"
  reason: "catch-all: outbound network emitted alongside allowed ops is allowed"
"#;

/// Write the agent-friendly policy posture into the policy dir so a freshly
/// onboarded agent can do routine work out of the box — without an operator
/// hand-authoring catch-all rules. The base stdlib stays strict (fail-closed);
/// these files are the *agent integration* layer that makes it usable:
///   - `06-agent-config-writable.yaml`: edit own config dirs (anti-lockout).
///   - `95-agent-catch-all.yaml`: fail-open-except-gates for shell/file/outbound.
///
/// Web fetch/search and MCP write are intentionally NOT broadened here — they
/// stay at the 15-agent-tools picto gate so trust-boundary-crossing tools keep
/// asking. Files are gommage-owned and overwritten on reinstall so the posture
/// stays current; an operator removes a file to opt that surface into strict mode.
pub(crate) fn write_agent_posture_policy(layout: &HomeLayout, dry_run: bool) -> Result<()> {
    let files: &[(&str, &str)] = &[
        ("06-agent-config-writable.yaml", AGENT_CARVE_OUT_YAML),
        ("95-agent-catch-all.yaml", AGENT_CATCH_ALL_YAML),
    ];
    for (name, contents) in files {
        let path = layout.policy_dir.join(name);
        write_text(&path, contents, dry_run)?;
    }
    println!(
        "{} agent posture: {} policy file(s) under {}",
        if dry_run { "plan" } else { "ok" },
        files.len(),
        layout.policy_dir.display()
    );
    Ok(())
}

fn install_claude(
    settings_path: &Path,
    layout: &HomeLayout,
    replace_hooks: bool,
    import_native_permissions: bool,
    dry_run: bool,
) -> Result<()> {
    let mut settings = read_json_object(settings_path)?;
    if import_native_permissions {
        import_claude_permissions(&settings, layout, replace_hooks, dry_run)?;
    }

    let matcher = claude_gommage_matcher(&settings);
    if matcher.is_empty() {
        println!("warn claude: no currently allowed Claude tools have Gommage capability mappers");
        return Ok(());
    }

    let group = serde_json::json!({
        "matcher": matcher,
        "hooks": [
            {
                "type": "command",
                "command": CLAUDE_GOMMAGE_HOOK_COMMAND,
                "timeout": 10
            }
        ]
    });
    install_json_hook_group(
        &mut settings,
        &["hooks", "PreToolUse"],
        group,
        replace_hooks,
        "claude",
    )?;

    write_json(settings_path, &settings, dry_run)?;
    println!(
        "ok claude: PreToolUse hook installed at {}",
        settings_path.display()
    );
    Ok(())
}

fn install_codex(
    hooks_path: &Path,
    config_path: &Path,
    replace_hooks: bool,
    dry_run: bool,
) -> Result<()> {
    let mut hooks = read_json_object(hooks_path)?;
    let group = serde_json::json!({
        "matcher": CODEX_GOMMAGE_MATCHER,
        "hooks": [
            {
                "type": "command",
                "command": CODEX_GOMMAGE_HOOK_COMMAND
            }
        ]
    });
    let hook_path = codex_pre_tool_use_path(&hooks);
    install_json_hook_group(&mut hooks, hook_path, group, replace_hooks, "codex")?;
    write_json(hooks_path, &hooks, dry_run)?;
    println!(
        "ok codex: PreToolUse hook installed at {}",
        hooks_path.display()
    );

    let mut config = read_toml_document(config_path)?;
    let sandbox_mode = config
        .get("sandbox_mode")
        .and_then(|v| v.as_str())
        .map(str::to_string);
    enable_codex_hooks_feature(&mut config);
    write_text(config_path, &config.to_string(), dry_run)?;
    println!(
        "ok codex: features.hooks enabled at {}",
        config_path.display()
    );
    if sandbox_mode.as_deref() == Some("danger-full-access") {
        println!(
            "warn codex: sandbox_mode is danger-full-access; Gommage's default Codex integration governs supported hook events only, so keep Codex sandboxing enabled for other tool boundaries"
        );
    }
    println!(
        "warn codex: native sandbox/approval config remains authoritative and is not converted to Gommage YAML"
    );
    Ok(())
}

fn import_claude_permissions(
    settings: &serde_json::Value,
    layout: &HomeLayout,
    force: bool,
    dry_run: bool,
) -> Result<()> {
    let deny_path = layout.policy_dir.join("05-claude-import.yaml");
    let deny_rules = native_permission_rules(settings, "/permissions/deny");
    let (translated_denies, skipped_denies) =
        translate_claude_native_rules(&deny_rules, translate_claude_permission_deny);
    write_claude_permission_import(
        &deny_path,
        "Claude Code permissions.deny",
        "Deny imports live before stdlib allow rules so native blocks remain fail-closed.",
        "claude-import-deny",
        "gommage",
        &translated_denies,
        force,
        dry_run,
    )?;
    if translated_denies.is_empty() {
        println!("warn claude: no importable native deny rules found");
    }
    if !skipped_denies.is_empty() {
        println!(
            "warn claude: skipped {} native deny rule(s) that need manual policy review",
            skipped_denies.len()
        );
    }

    let allow_rules = native_permission_rules(settings, "/permissions/allow");
    let (translated_allows, skipped_allows) =
        translate_claude_native_rules(&allow_rules, translate_claude_permission_allow);
    if !allow_rules.is_empty() {
        let allow_path = layout.policy_dir.join("90-claude-allow-import.yaml");
        write_claude_permission_import(
            &allow_path,
            "Claude Code permissions.allow",
            "Allow imports load late so Gommage hard-stop, deny, and ask rules win first.",
            "claude-import-allow",
            "allow",
            &translated_allows,
            force,
            dry_run,
        )?;
        if translated_allows.is_empty() {
            println!("warn claude: no narrow native allow rules were imported");
        }
        if !skipped_allows.is_empty() {
            println!(
                "warn claude: skipped {} native allow rule(s) that need manual policy review",
                skipped_allows.len()
            );
        }
    }
    Ok(())
}

pub(crate) struct NativePermissionImport {
    raw: String,
    capability: String,
}

pub(crate) fn native_permission_rules(settings: &serde_json::Value, pointer: &str) -> Vec<String> {
    settings
        .pointer(pointer)
        .and_then(|v| v.as_array())
        .into_iter()
        .flatten()
        .filter_map(|v| v.as_str().map(str::to_string))
        .collect()
}

pub(crate) fn translate_claude_native_rules(
    rules: &[String],
    translate: fn(&str) -> Option<String>,
) -> (Vec<NativePermissionImport>, Vec<String>) {
    let mut translated = Vec::new();
    let mut skipped = Vec::new();
    for raw in rules {
        match translate(raw) {
            Some(capability) => translated.push(NativePermissionImport {
                raw: raw.clone(),
                capability,
            }),
            None => skipped.push(raw.clone()),
        }
    }
    (translated, skipped)
}

#[allow(clippy::too_many_arguments)]
fn write_claude_permission_import(
    import_path: &Path,
    source_label: &str,
    ordering_note: &str,
    name_prefix: &str,
    decision: &str,
    translated: &[NativePermissionImport],
    force: bool,
    dry_run: bool,
) -> Result<()> {
    if translated.is_empty() {
        return Ok(());
    }

    let grouped = group_native_permission_imports(translated);
    let mut yaml = String::new();
    yaml.push_str(&format!(
        "# Generated by `gommage quickstart` from {source_label}.\n"
    ));
    yaml.push_str(
        "# Review before sharing; native permission syntax is broader than Gommage capabilities.\n",
    );
    yaml.push_str(&format!("# {ordering_note}\n\n"));
    for (index, imported) in grouped.iter().enumerate() {
        yaml.push_str(&format!("- name: {name_prefix}-{:02}\n", index + 1));
        yaml.push_str(&format!("  decision: {decision}\n"));
        yaml.push_str("  match:\n");
        yaml.push_str("    any_capability:\n");
        yaml.push_str(&format!(
            "      - {}\n",
            serde_json::to_string(&imported.capability)?
        ));
        yaml.push_str(&format!(
            "  reason: {}\n\n",
            serde_json::to_string(&format!(
                "imported from {source_label}: {}",
                imported.raws.join(", ")
            ))?
        ));
    }

    if import_path.exists() && !force {
        let current = std::fs::read_to_string(import_path)?;
        if current == yaml {
            println!(
                "ok claude: native permission import already current at {}",
                import_path.display()
            );
        } else {
            println!(
                "warn claude: {} exists; use --replace-hooks to refresh imported native permissions",
                import_path.display()
            );
        }
    } else {
        write_text(import_path, &yaml, dry_run)?;
        println!(
            "ok claude: imported {} native rule(s) as {} capability rule(s) into {}",
            translated.len(),
            grouped.len(),
            import_path.display()
        );
    }
    Ok(())
}

struct NativePermissionImportGroup {
    capability: String,
    raws: Vec<String>,
}

fn group_native_permission_imports(
    translated: &[NativePermissionImport],
) -> Vec<NativePermissionImportGroup> {
    let mut groups: Vec<NativePermissionImportGroup> = Vec::new();
    for imported in translated {
        if let Some(group) = groups
            .iter_mut()
            .find(|group| group.capability == imported.capability)
        {
            group.raws.push(imported.raw.clone());
        } else {
            groups.push(NativePermissionImportGroup {
                capability: imported.capability.clone(),
                raws: vec![imported.raw.clone()],
            });
        }
    }
    groups
}

pub(crate) fn translate_claude_permission_deny(raw: &str) -> Option<String> {
    translate_claude_permission_specifier(raw)
}

pub(crate) fn translate_claude_permission_allow(raw: &str) -> Option<String> {
    translate_claude_permission_specifier(raw)
}

fn translate_claude_permission_specifier(raw: &str) -> Option<String> {
    if let Some((tool, value)) = raw.split_once('(') {
        let value = value.strip_suffix(')')?;
        let capability = match tool {
            "Read" | "Glob" => format!("fs.read:{}", normalize_native_path_pattern(value)),
            "Grep" => format!("fs.search:{}", normalize_native_path_pattern(value)),
            "Write" | "Edit" | "MultiEdit" | "NotebookEdit" => {
                format!("fs.write:{}", normalize_native_path_pattern(value))
            }
            "Bash" => format!("proc.exec:{}", normalize_bash_permission_pattern(value)),
            "WebFetch" => format!(
                "net.fetch:{}",
                value.strip_prefix("domain:").unwrap_or(value)
            ),
            tool if tool.starts_with("mcp__") => format!("mcp.call:{tool}"),
            _ => return None,
        };
        return Some(capability);
    }

    let capability = match raw {
        "*" => "**".to_string(),
        "Read" | "Glob" => "fs.read:**".to_string(),
        "Grep" => "fs.search:**".to_string(),
        "Write" | "Edit" | "MultiEdit" | "NotebookEdit" => "fs.write:**".to_string(),
        "Bash" => "proc.exec:*".to_string(),
        "WebFetch" => "net.fetch:*".to_string(),
        "WebSearch" => "net.search:web".to_string(),
        tool if tool.starts_with("mcp__") && tool.matches("__").count() >= 2 => {
            format!("mcp.call:{tool}")
        }
        _ => return None,
    };
    Some(capability)
}

fn normalize_native_path_pattern(raw: &str) -> String {
    if raw == "*" || raw == "**" {
        "**".to_string()
    } else if raw == "~" {
        "${HOME}".to_string()
    } else if let Some(rest) = raw.strip_prefix("~/") {
        format!("${{HOME}}/{rest}")
    } else if raw == "." || raw == "./" {
        "${EXPEDITION_ROOT}/**".to_string()
    } else if let Some(rest) = raw.strip_prefix("./") {
        format!("${{EXPEDITION_ROOT}}/{rest}")
    } else {
        raw.to_string()
    }
}

fn normalize_bash_permission_pattern(raw: &str) -> String {
    raw.replace(":*", "*")
}

pub(crate) fn claude_gommage_matcher(settings: &serde_json::Value) -> String {
    const MAPPED: &[&str] = &[
        "Bash",
        "Read",
        "Write",
        "Edit",
        "MultiEdit",
        "NotebookEdit",
        "Glob",
        "Grep",
        "WebFetch",
        "WebSearch",
        "mcp__.*",
    ];
    let allow = settings
        .pointer("/permissions/allow")
        .and_then(|v| v.as_array());
    let mut tools = Vec::new();
    for tool in MAPPED {
        let allowed = allow.is_none_or(|rules| claude_allow_covers_tool(rules, tool));
        if allowed {
            tools.push(*tool);
        }
    }
    tools.join("|")
}

fn claude_allow_covers_tool(rules: &[serde_json::Value], tool: &str) -> bool {
    rules.iter().filter_map(|v| v.as_str()).any(|rule| {
        rule == "*"
            || rule == tool
            || rule
                .strip_prefix(tool)
                .is_some_and(|rest| rest.starts_with('('))
            || (tool == "mcp__.*" && rule.starts_with("mcp__"))
    })
}

fn install_json_hook_group(
    root: &mut serde_json::Value,
    path: &[&str],
    group: serde_json::Value,
    replace_hooks: bool,
    agent_name: &str,
) -> Result<()> {
    let pre_tool_use = ensure_array_path(root, path)?;
    if replace_hooks {
        pre_tool_use.clear();
    } else {
        pre_tool_use.retain(|entry| !json_hook_entry_contains_command(entry, "gommage"));
        if !pre_tool_use.is_empty() {
            println!(
                "warn {agent_name}: preserving existing PreToolUse hook group(s); use --replace-hooks to let Gommage own the hook surface"
            );
        }
    }
    pre_tool_use.push(group);
    Ok(())
}

fn ensure_array_path<'a>(
    root: &'a mut serde_json::Value,
    path: &[&str],
) -> Result<&'a mut Vec<serde_json::Value>> {
    let mut current = root;
    for key in &path[..path.len() - 1] {
        if !current.is_object() {
            anyhow::bail!("expected JSON object while creating {key}");
        }
        let object = current.as_object_mut().expect("checked object");
        current = object
            .entry((*key).to_string())
            .or_insert_with(|| serde_json::Value::Object(serde_json::Map::new()));
    }
    let key = path[path.len() - 1];
    if !current.is_object() {
        anyhow::bail!("expected JSON object while creating {key}");
    }
    let value = current
        .as_object_mut()
        .expect("checked object")
        .entry(key.to_string())
        .or_insert_with(|| serde_json::Value::Array(Vec::new()));
    if !value.is_array() {
        anyhow::bail!("{key} exists but is not an array");
    }
    Ok(value.as_array_mut().expect("checked array"))
}

fn json_hook_entry_contains_command(entry: &serde_json::Value, needle: &str) -> bool {
    entry
        .get("hooks")
        .and_then(|v| v.as_array())
        .is_some_and(|hooks| {
            hooks.iter().any(|hook| {
                hook.get("command")
                    .and_then(|v| v.as_str())
                    .is_some_and(|command| command.to_ascii_lowercase().contains(needle))
            })
        })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn broad_write_native_permissions_collapse_to_one_capability() {
        let rules = vec![
            "Write".to_string(),
            "Edit".to_string(),
            "NotebookEdit(*)".to_string(),
            "MultiEdit(**)".to_string(),
        ];

        let (translated, skipped) =
            translate_claude_native_rules(&rules, translate_claude_permission_allow);
        let grouped = group_native_permission_imports(&translated);

        assert!(skipped.is_empty());
        assert_eq!(grouped.len(), 1);
        assert_eq!(grouped[0].capability, "fs.write:**");
        assert_eq!(
            grouped[0].raws,
            vec!["Write", "Edit", "NotebookEdit(*)", "MultiEdit(**)"]
        );
    }

    #[test]
    fn native_star_path_is_normalized_to_recursive_glob() {
        assert_eq!(
            translate_claude_permission_allow("Read(*)").as_deref(),
            Some("fs.read:**")
        );
        assert_eq!(
            translate_claude_permission_allow("Write(*)").as_deref(),
            Some("fs.write:**")
        );
    }

    #[test]
    fn agent_install_generates_posture_policy_that_parses() {
        let tmp = tempfile::tempdir().unwrap();
        let layout = HomeLayout::at(tmp.path());
        layout.ensure().unwrap();

        write_agent_posture_policy(&layout, false).unwrap();

        for name in ["06-agent-config-writable.yaml", "95-agent-catch-all.yaml"] {
            assert!(
                layout.policy_dir.join(name).exists(),
                "expected generated posture file {name}"
            );
        }

        let mut env = std::collections::HashMap::new();
        env.insert("HOME".to_string(), "/home/test".to_string());
        env.insert("EXPEDITION_ROOT".to_string(), "/home/test/proj".to_string());
        let policy = gommage_core::Policy::load_from_dir(&layout.policy_dir, &env).unwrap();

        for rule in [
            "agent-config-writable-claude",
            "agent-config-writable-gommage",
            "agent-catch-all-proc-exec",
            "agent-catch-all-fs-write",
        ] {
            assert!(
                policy.rules.iter().any(|r| r.name == rule),
                "expected posture rule {rule}"
            );
        }
    }

    #[test]
    fn agent_posture_dry_run_writes_nothing() {
        let tmp = tempfile::tempdir().unwrap();
        let layout = HomeLayout::at(tmp.path());
        layout.ensure().unwrap();

        write_agent_posture_policy(&layout, true).unwrap();

        assert!(
            !layout.policy_dir.join("95-agent-catch-all.yaml").exists(),
            "dry-run must not write posture files"
        );
    }
}
